[functions]
  node_bundler = "esbuild"

[build]
  publish = "dist"
  command = "npm run build"

# Configuration pour Netlify Forms
[[forms]]
  name = "contact"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/entry"
  status = 200